### PR TITLE
test

### PR DESCRIPTION
**Pull request by codeofsumit**
---
name: Tutorial PR
about: Making a Pull Request for the ZEIT Getting Started tutorial?

---

If you're making a pull request for a part of the tutorial on https://zeit.co to setup Github Integration, that's awesome! You're almost there 🎉

Make sure of these 2 things before making the pull request:

1.  This Pull Request is against your own fork of the project and not the [zeit/now-github-starter](https://github.com/zeit/now-github-starter) repo
2.  Your Pull Request includes a `now.json` file with configuration settings. To get started, the file can even just contain `{}` and nothing else.

### CODE REVIEW

**Comment by codeofsumit** [comment]
hm.
THe links are broken and the deployments are not visible in now desktop 🤔

**Comment by matheuss** [comment]
@codeofsumit I'm sorry that the onboarding mislead you – you should submit a PR to your fork, not to this repo.

**Comment by matheuss** [comment]
Would you mind to chat with @timothyis ti help us improve the flow? 🙏

**Comment by codeofsumit** [comment]
Hi @matheuss, of course!
Also I did the PR against my own Repo:
https://github.com/codeofsumit/now-github-starter/pull/1

Deployment works but, the "Details" button functions correctly but the link from the `now` bot are still broken and lead to 404
It's this link:
https://zeit.co/docs/features/github-integration?utm_source=automated&utm_medium=github&utm_campaign=now_bot

**Comment by pranaygp** [comment]
Hey @codeofsumit We caught that bug and have an issue to track it internally.

The correct link should be https://zeit.co/docs/features/now-for-github if you're interested in learning more 😄

**Pull request closed without merging**
